package com.example.catpuccino_back.models.enums;

public enum Raza {
    PERSA, AZUL_RUSO, SIAMES, ANGORA_TURCO, SIBERIANO, MAINE_COON, BENGALI, BRITANICO_DE_PELO_CORTO, SCOTTISH_FOLD,
    SPHYNX, RAGDOLL, ABISINIO, BIRMANO, AMERICANO_DE_PELO_CORTO, EXOTICO_DE_PELO_CORTO, MIXTO,
}
